# Generated by Django 5.2.1 on 2025-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butikk_app', '0003_alter_productinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(upload_to='butikk_app/images'),
        ),
    ]
